### ISSUE TITLE
Добавить команду /фича реквест  и /фичи

### ISSUE THREAD

**Issue by Masterstop** [Xoma163/xoma163site#30]
Команда /фича реквест на пересланном сообщении - после модерации добавляет реквест фичи в блок /фичи
Команда /фичи - выводит все нереализованные /фичи реквесты

Команды для админа:
/фича N одобрить, где N номер созданной фичи
/фича N реализовать, где N номер одобренной фичи
/фича N отменить, где N номер одобренной фичи

**Comment by Xoma163** [comment]
Это будет сложно прикрутить. Проще сделать /фича и пересланное сообщение - суть фичи. Добавится в базу, оттуда я вручную перенесу на гит. Вряд ли смогу сделать это автоматически

Вести ишю в самом Петровиче будет сложно
