### ISSUE TITLE
Ачивки

### ISSUE THREAD

**Issue by Xoma163** [Xoma163/xoma163site#93]

**Comment by Maksim631** [comment]
What type of "ХЕЛП" do u need?

**Comment by Xoma163** [comment]
> What type of "ХЕЛП" do u need?

Задача очень сложная и может выполниться только после других определённых команд, в случае, если мы рассматриваем веб-часть.
Если нет - нужны идеи для ачивок с реально низкими вероятностями выпадения или те, которые нужно заслужить, например, как Женя, который хочет "пройти" Петровича. Но грузить базу всеми победами во всех ставках и каждый раз опрашивать - не хочется, например.

**Comment by Xoma163** [comment]
> What type of "ХЕЛП" do u need?

Если ачивка выполнилась, нужно запускать особую обработку этого события и присылать пользователю уведомление. Нужна команда /ачивки - типа мои. Нужно продумать, скрыты ли ачивки или нет? Может ли пользователь стремиться к ним или они чёрный ящик? Как выводить ачивки? Только названия или детальное описание? Короче вопросов много
